[package]
name = "cargo-authors"
version = "0.3.1"
authors = ["Henning-K <henning.kowalk962@web.de>"]

license = "MIT/Apache-2.0"
keywords = ["cargo", "authors", "subcommand"]
homepage = "https://github.com/Henning-K/cargo-authors"
repository = "https://github.com/Henning-K/cargo-authors"
readme = "README.md"
description = """
A subcommand for cargo that lists all the authors of all the dependencies
of the crate in your current working directory.
Simply install, then navigate to the directory of a crate and run `cargo authors`
"""

[dependencies]
cargo = "0.22"
error-chain = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
docopt = "0.8"
