[package]
name = "cargo-authors"
version = "0.0.1"
authors = ["Henning-K <henning.kowalk962@web.de>"]

license = "MIT/Apache-2.0"
keywords = ["cargo", "authors", "subcommand"]
repository = "https://github.com/Henning-K/cargo-authors"
readme = "README.md"
description = """
A subcommand for cargo that lists all the authors of all the dependencies
of the crate in your current working directory.
Simply install, then navigate to the directory of a crate and run `cargo authors`
"""

[dependencies]
cargo = "0.16"
rustc-serialize = "0.3"
error-chain = "0.9"
