[package]
name = "cargo-authors"
version = "0.1.0"
authors = ["Henning-K <henning.kowalk962@web.de>"]

description = "Placeholder for now. Actual crate coming soon(tm)"
repository = "https://github.com/Henning-K/cargo-authors"
readme = "README.md"

keywords = ["cargo", "authors", "subcommand"]

license = "MIT/Apache-2.0"

[dependencies]
cargo = "0.16"
rustc-serialize = "0.3"
